#!/usr/bin/env python3
import os
import sys
import getopt
from time import sleep

VERSION = "0.1"
PROGRAM = os.path.basename(__file__)
USAGE = f"""\
{PROGRAM} version {VERSION}.
Display text or graphic to an attached LCD.
Syntax: {PROGRAM} [OPTION] [TEXT]
OPTION:
-B      Turn backlight on.
-b      Turn backlight off.
-d op   Run a demo with option op (default "all") and ignore all other options.
-h      Display this help and exit.
-i      Initialize/reset LCD (effectively clear the screen).
-p      Print LCD parameters.
-t      LCD type (required). Supported type are hd44780, hd44780opi, st7920.
-x      Clear the LCD screen.
-r      Restore GPIO settings (default is not).
-l n    Move text cursor to line n (start from 1, default 1).
-c n    Move text cursor to column n (if supported, start from 1, default 1).
"""

def main():
	# Default settings.
	lcdType = None
	init = False
	backlight = None
	clear = False
	demo = None
	printParams = False
	line = 1
	col = 1
	cleanup = False
	lcd = None

	# Process command line arguments.
	if len(sys.argv) == 1:
		print(USAGE)
		sys.exit(0)
	# Handle commandline arguments.
	try:
		opts, args = getopt.getopt(sys.argv[1:], 'bBc:d:hil:prt:x')
	except getopt.error as err:
		print(f'ERROR: {str(err)}. Use "-h" for usage.', file = sys.stderr)
		sys.exit(1)

	for o, v in opts:
		if o == '-h':
			print(USAGE)
			sys.exit(0)
		elif o == '-b':
			backlight = False
		elif o == '-B':
			backlight = True
		elif o == '-c':
			col = int(v)
		elif o == '-d':
			demo = v
		elif o == '-i':
			init = True
		elif o == '-l':
			line = int(v)
		elif o == '-p':
			printParams = True
		elif o == '-r':
			cleanup = True
		elif o == '-t':
			lcdType = v.lower()
		elif o == '-x':
			clear = True
		else:
			print('ERROR: Unknown option. Use "-h" for usage.', file = sys.stderr);
			sys.exit(2)

	text = ' '.join(args)

	if lcdType is None:
		print('ERROR: Missing LCD type.', file = sys.stderr)
		sys.exit(2)
	elif lcdType == "st7920":
		from st7920 import ST792012864SPI
		lcd = ST792012864SPI()
	elif lcdType == "hd44780":
		from hd44780 import HD44780
		lcd = HD44780()
	elif lcdType == "hd44780opi":
		from hd44780opi import HD44780OPiH616
		lcd = HD44780OPiH616()
	else:
		print('ERROR: unsupported LCD.', file = sys.stderr)
		sys.exit(3)

	if lcd is None:
		print('ERROR: Unable to initialize an LCD.', file = sys.stderr)
		sys.exit(4)
	else:
		if printParams:
			lcd.printParams()
		if demo:
			lcd.demo(option = demo)
			sys.exit(0)
		if init:
			lcd.init()
		if backlight is not None:
			lcd.backlight(backlight)
		if clear:
			lcd.clearScreen()
		if len(text):
			lcd.printText(text, line = line, col = col)
		if cleanup:
			lcd.cleanup()
 
if __name__ == '__main__':
	main()

